### ISSUE TITLE
Extension for Visual Studio Code

### ISSUE THREAD

**Issue by rjopek** [cairo-list/cairo-list#19]
Proposal for a new project for Cairo, Extension for Visual Studio Code.
It is very useful in certain circumstances.

**Comment by stuaxo** [comment]
For Jupyter-cairo I wanted some debug facilities for Cairo, but never had the time to implement them.

It would be great to be able to render paths on top of a grid to show scale, also things like the locations and types of nodes on paths etc.

**Comment by stuaxo** [comment]
Vscode extensions are in TypeScript which isn't too bad, I started implementing a matplotlib extension, based here you can look at - (the code is very prototypey!)

https://github.com/uktrade/vscode-matplotlib/

This works by generating pngs or svgs and sending them over a socket, then there is TypeScript code at the VSCode end to display it.

There's another, more complete extension which uses Canvas in the VSCode end, which could be interesting, since both Canvas and Cairographics have a similar API.

**Comment by rjopek** [comment]
For starters, extensions will provide typing features with a short description.

**Comment by rjopek** [comment]
As you type, it tells you which functions to use.

**Comment by rjopek** [comment]
The python or pycairo environment allows this.
When it comes to C/C++ there will be differences.

I also use such a service for my Harbor language, if I write a Harbor function I have a hint and I can quickly find the right function (I'm old as coal so I forget a lot) it's very useful.

For example, Harbour has 14 744 installs from the Visual Studio Code Marketplace, so there's interest.
The same should be done for functions in Cairo.

Search for the appropriate Template.

**Comment by rjopek** [comment]
Sorry Stuart but I'm critical of python, luckily I've never written an application in python and I hope I never will.
